### ISSUE TITLE
mhauri/mhauri-hipchat 0.3.0 requires magento-hackathon/magento-composer-installer 2.* -> no matching package found.

### ISSUE THREAD

**Issue by Flyingmana** [mhauri/magento-hipchat#2]
:(

I require a different version then 2.*

**Comment by mhauri** [comment]
@Flyingmana  can you check if it works now for you?

**Comment by Flyingmana** [comment]
this should work now, at least as long I use the installer as part of the project, and not as global composer plugin (targeted for next year)

**Comment by Flyingmana** [comment]
I personally recommend to use it as "suggest" not as "require", maybe I should write a blogpost about this sometime in the future...

**Comment by mhauri** [comment]
@Flyingmana good point with the suggest, will take care of that

**Comment by Flyingmana** [comment]
ping
(as Iam just stumbled over this again today)
and maybe add a 0.3.1 tag

**Comment by mhauri** [comment]
@Flyingmana thx for ping me about this issue, it's fixed in release 0.3.1
